In [1]:
# Library
# 这个是用来判断点在不在多边形里面的库，同时绘制点和多边形
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon
# 这里是用这个来读取shapefile文件
import shapefile
import pandas as pd
import numpy as np

In [7]:
# Load the shapefile information
sf = shapefile.Reader("../2019ParcelPointsNoDups/2019ParcelPointsNoDups.shp") # note, no suffix, all 3 files are used
recs = sf.records()
shapes = sf.shapes()

In [8]:
recs

[Record #0: ['0100001000', '', '0100001000', 'PASCUCCI CARLO', '104 A 104', 'PUTNAM', 'ST', '', '02128', 'R3', '105', 1150, '195 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'Y', 3353, 2202, 541200.0, 129900, 411300, 5704.25, 3.0, '0100001000', '104 A 104 PUTNAM ST, 02128', 'EAST BOSTON', 210.2109375, 65.8426763, 210.2109375, 65.8426762964, 1, -71.032587507, 42.3793853109],
 Record #1: ['0100002000', '', '0100002000', 'ATANASOV DANIEL', '197', 'LEXINGTON', 'ST', '', '02128', 'R3', '105', 1150, '197 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'N', 3299, 2307, 596100.0, 121000, 475100, 6282.89, 3.0, '0100002000', '197   LEXINGTON ST, 02128', 'EAST BOSTON', 197.875, 64.69736635, 197.875, 64.6973663526, 2, -71.0325209187, 42.3794119758],
 Record #2: ['0100003000', '', '0100003000', 'CHEVARRIA ANA S', '199', 'LEXINGTON', 'ST', '', '02128', 'R3', '105', 1150, '199 LEXINGTON ST', 'EAST BOSTON MA', '02128', 'N', 3392, 2268, 542500.0, 121400, 421100, 5717.95, 3.0, '0100003000', '199   LEXINGTON ST, 

In [9]:
df = pd.DataFrame(recs) 

In [10]:
df.head()

0 1           2                      3          4          5   6  \
0  0100001000    0100001000         PASCUCCI CARLO  104 A 104     PUTNAM  ST   
1  0100002000    0100002000        ATANASOV DANIEL        197  LEXINGTON  ST   
2  0100003000    0100003000        CHEVARRIA ANA S        199  LEXINGTON  ST   
3  0100004000    0100004000  MADDALENI JAMES E, TS        201  LEXINGTON  ST   
4  0100005000    0100005000      DIGIROLAMO JOHN A        203  LEXINGTON  ST   

  7      8   9   10    11                12              13     14 15    16  \
0    02128  R3  105  1150  195 LEXINGTON ST  EAST BOSTON MA  02128  Y  3353   
1    02128  R3  105  1150  197 LEXINGTON ST  EAST BOSTON MA  02128  N  3299   
2    02128  R3  105  1150  199 LEXINGTON ST  EAST BOSTON MA  02128  N  3392   
3    02128  R3  105  1150      PO BOX 557 #      EVERETT MA  02149  N  3108   
4    02128  R2  104  2010  203 LEXINGTON ST  EAST BOSTON MA  02128  Y  3700   

     17        18      19      20       21   22          23  \
0  2202  541200.0  129900  411300  5704.25  3.0  0100001000   
1  2307  596100.0  121000  475100  6282.89  3.0  0100002000   
2  2268  542500.0  121400  421100  5717.95  3.0  0100003000   
3  2028  518300.0  121900  396400  5462.88  3.0  0100004000   
4  2546  528400.0  135900  392500  5569.34  3.0  0100005000   

                           24           25          26          27  \
0  104 A 104 PUTNAM ST, 02128  EAST BOSTON  210.210938   65.842676   
1   197   LEXINGTON ST, 02128  EAST BOSTON  197.875000   64.697366   
2   199   LEXINGTON ST, 02128  EAST BOSTON  195.144531   64.345174   
3   201   LEXINGTON ST, 02128  EAST BOSTON  203.187500   64.898348   
4   203   LEXINGTON ST, 02128  EAST BOSTON  367.007812  102.429328   

           28          29  30         31         32  
0  210.210938   65.842676   1 -71.032588  42.379385  
1  197.875000   64.697366   2 -71.032521  42.379412  
2  195.144531   64.345174   3 -71.032455  42.379436  
3  203.187500   64.898348   4 -71.032390  42.379463  
4  367.007812  102.429328   5 -71.032282  42.379430

In [6]:
test = df[df[10].isin([986])]
pd.set_option('display.max_columns', None)
test.head(20)

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
Index: []

In [15]:
df_ptype = df[[10, 32,31]]
df[10] = df[10].astype(np.int32)
df[32] = df[32].astype(np.float64)
df[31] = df[31].astype(np.float64)
# df_ptype = pd.to_numeric(df_ptype)
# df_ptype = pd.DataFrame(df_ptype)
df_ptype

10         32         31
0       105  42.379385 -71.032588
1       105  42.379412 -71.032521
2       105  42.379436 -71.032455
3       105  42.379463 -71.032390
4       104  42.379430 -71.032282
...     ...        ...        ...
171917  902  42.340875 -71.166619
171918  132  42.340518 -71.166668
171919  105  42.340526 -71.166393
171920  319  42.340277 -71.166450
171921  985  42.340758 -71.166971

[171922 rows x 3 columns]

In [17]:
    df_data_1 = df_ptype[df_ptype[10].isin([986])]
    df_data_1 = df_data_1.values.astype(np.float64)
    for l in df_data_1:
        print(l)

[986.          42.37970363 -71.02339356]
[986.          42.3797826  -71.02326725]
[986.          42.38031825 -71.02383026]
[986.          42.37996442 -71.02337051]
[986.          42.3800514  -71.02365936]
[986.          42.37989714 -71.02380408]
[986.          42.39615117 -71.01386321]
[986.          42.38483221 -71.02109312]
[986.          42.38491843 -71.02061511]
[986.          42.38665205 -71.02002284]
[986.          42.38560424 -71.02176099]
[986.          42.3832332  -71.02273371]
[986.          42.38150453 -71.02395088]
[986.          42.38376266 -70.99664383]
[986.          42.3863519  -71.00551577]
[986.          42.38664268 -71.00606604]
[986.          42.3845444  -70.99505767]
[986.          42.37032867 -71.03698309]
[986.          42.37032287 -71.0367576 ]
[986.          42.37139771 -71.03553594]
[986.          42.37135381 -71.03508997]
[986.          42.37309298 -71.03343689]
[986.          42.37469116 -71.03153   ]
[986.          42.37665453 -71.02928979]
[986.          4

In [27]:
df_data_1 = df_ptype[df_ptype[10].isin([986])]
vacant1 = df_data_1[[32, 31]].values.astype(np.float64)
count = 1
for l in vacant1:
    print(str(count) + " " + str(l[0])+","+str(l[1]))
    count += 1

1 42.3797036345,-71.0233935644
2 42.3797825963,-71.0232672506
3 42.38031825,-71.0238302569
4 42.3799644161,-71.0233705139
5 42.3800514014,-71.0236593629
6 42.3798971397,-71.0238040828
7 42.3961511724,-71.0138632142
8 42.3848322068,-71.0210931163
9 42.3849184266,-71.0206151105
10 42.3866520521,-71.0200228396
11 42.3856042416,-71.0217609865
12 42.3832331968,-71.0227337115
13 42.3815045297,-71.0239508781
14 42.3837626634,-70.9966438329
15 42.3863518984,-71.0055157739
16 42.3866426792,-71.0060660447
17 42.3845443986,-70.9950576735
18 42.3703286728,-71.0369830871
19 42.3703228729,-71.0367576031
20 42.371397712,-71.0355359366
21 42.3713538053,-71.0350899687
22 42.3730929794,-71.0334368857
23 42.3746911636,-71.031530004
24 42.3766545262,-71.02928979
25 42.377545041,-71.0282528268
26 42.374661984,-71.0309894396
27 42.3756905057,-71.0253478257
28 42.3757162853,-71.0272129585
29 42.3777146608,-71.0274827352
30 42.3783152963,-71.0267425798
31 42.3789823755,-71.0259539604
32 42.3794236566,-71.0253

In [25]:
df_data_1 = df_ptype[df_ptype[10].isin([962])]
vacant1 = df_data_1[[32, 31]].values.astype(np.float64)
count = 1
for l in vacant1:
    print(str(count) + " " + str(l[0])+","+str(l[1]))
    count += 1

1 42.3496621025,-71.0606918813
2 42.3431607363,-71.0537114454
3 42.3429510232,-71.0538719643
4 42.3347877843,-71.0439592789
5 42.3473558745,-71.0353563793
6 42.3469468633,-71.0364315678
7 42.3435920989,-71.0362168409
8 42.3436458388,-71.0346317766
9 42.3285781524,-71.066917502
10 42.3348247814,-71.0700084905
11 42.3335898134,-71.0716637777
12 42.3304045238,-71.0850609433
13 42.3202999784,-71.0461353812
14 42.3115797688,-71.0633750982
15 42.3646896734,-71.1220859014
16 42.3579923473,-71.1473648712


In [89]:
# Build a list to hold the ploygon represent the subsurb
sub_plon = []
for item in shapes:
    # Using the points information to draw the ploygon
    polygon = Polygon(item.points)
    sub_plon.append(polygon)
# Drow one of the subsurb
sub_plon[0]

ValueError: A LinearRing must have at least 3 coordinate tuples